import { Game } from "./types";

export const mockGames: Game[] = [
  // Live games
  {
    id: "1",
    homeTeam: { id: "NYA", name: "New York Atlas", abbreviation: "NYA", record: "8-3" },
    awayTeam: { id: "PHL", name: "Philadelphia Waterdogs", abbreviation: "PHL", record: "7-4" },
    homeScore: 9,
    awayScore: 7,
    status: "live",
    period: "3rd",
    clock: "6:42",
    date: "2026-02-27",
    time: "7:00 PM ET",
    venue: "UBS Arena, Elmont NY",
    league: "PLL",
  },
  {
    id: "2",
    homeTeam: { id: "BOS", name: "Boston Cannons", abbreviation: "BOS", record: "6-5" },
    awayTeam: { id: "CAL", name: "California Redwoods", abbreviation: "CAL", record: "9-2" },
    homeScore: 11,
    awayScore: 11,
    status: "live",
    period: "4th",
    clock: "2:15",
    date: "2026-02-27",
    time: "8:00 PM ET",
    venue: "Harvard Stadium, Boston MA",
    league: "PLL",
  },
  // Final games today
  {
    id: "3",
    homeTeam: { id: "ATL", name: "Atlas LC", abbreviation: "ATL", record: "10-2" },
    awayTeam: { id: "CHR", name: "Chrome LC", abbreviation: "CHR", record: "5-7" },
    homeScore: 14,
    awayScore: 8,
    status: "final",
    date: "2026-02-27",
    time: "4:00 PM ET",
    venue: "Navy-Marine Corps Memorial Stadium",
    league: "PLL",
  },
  {
    id: "4",
    homeTeam: { id: "REH", name: "Redwoods LC", abbreviation: "RED", record: "7-5" },
    awayTeam: { id: "WAT", name: "Waterdogs LC", abbreviation: "WAT", record: "6-6" },
    homeScore: 10,
    awayScore: 12,
    status: "final",
    date: "2026-02-27",
    time: "2:00 PM ET",
    venue: "Subaru Park, Chester PA",
    league: "PLL",
  },
  // Upcoming schedule
  {
    id: "5",
    homeTeam: { id: "DEN", name: "Denver LC", abbreviation: "DEN", record: "8-3" },
    awayTeam: { id: "NYA", name: "New York Atlas", abbreviation: "NYA", record: "8-3" },
    homeScore: 0,
    awayScore: 0,
    status: "scheduled",
    date: "2026-02-28",
    time: "7:00 PM ET",
    venue: "Dick's Sporting Goods Park, Commerce City CO",
    league: "PLL",
  },
  {
    id: "6",
    homeTeam: { id: "PHL", name: "Philadelphia Waterdogs", abbreviation: "PHL", record: "7-4" },
    awayTeam: { id: "BOS", name: "Boston Cannons", abbreviation: "BOS", record: "6-5" },
    homeScore: 0,
    awayScore: 0,
    status: "scheduled",
    date: "2026-02-28",
    time: "9:00 PM ET",
    venue: "Subaru Park, Chester PA",
    league: "PLL",
  },
  {
    id: "7",
    homeTeam: { id: "CAL", name: "California Redwoods", abbreviation: "CAL", record: "9-2" },
    awayTeam: { id: "ATL", name: "Atlas LC", abbreviation: "ATL", record: "10-2" },
    homeScore: 0,
    awayScore: 0,
    status: "scheduled",
    date: "2026-03-01",
    time: "5:00 PM ET",
    venue: "Snapdragon Stadium, San Diego CA",
    league: "PLL",
  },
  {
    id: "8",
    homeTeam: { id: "CHR", name: "Chrome LC", abbreviation: "CHR", record: "5-7" },
    awayTeam: { id: "WAT", name: "Waterdogs LC", abbreviation: "WAT", record: "6-6" },
    homeScore: 0,
    awayScore: 0,
    status: "scheduled",
    date: "2026-03-01",
    time: "7:30 PM ET",
    venue: "Gillette Stadium, Foxborough MA",
    league: "PLL",
  },
  // Past results
  {
    id: "9",
    homeTeam: { id: "NYA", name: "New York Atlas", abbreviation: "NYA", record: "8-3" },
    awayTeam: { id: "CHR", name: "Chrome LC", abbreviation: "CHR", record: "5-7" },
    homeScore: 15,
    awayScore: 9,
    status: "final",
    date: "2026-02-22",
    time: "7:00 PM ET",
    venue: "UBS Arena, Elmont NY",
    league: "PLL",
  },
  {
    id: "10",
    homeTeam: { id: "CAL", name: "California Redwoods", abbreviation: "CAL", record: "9-2" },
    awayTeam: { id: "DEN", name: "Denver LC", abbreviation: "DEN", record: "8-3" },
    homeScore: 13,
    awayScore: 10,
    status: "final",
    date: "2026-02-22",
    time: "9:00 PM ET",
    venue: "Snapdragon Stadium, San Diego CA",
    league: "PLL",
  },
  {
    id: "11",
    homeTeam: { id: "BOS", name: "Boston Cannons", abbreviation: "BOS", record: "6-5" },
    awayTeam: { id: "ATL", name: "Atlas LC", abbreviation: "ATL", record: "10-2" },
    homeScore: 8,
    awayScore: 11,
    status: "final",
    date: "2026-02-21",
    time: "7:00 PM ET",
    venue: "Harvard Stadium, Boston MA",
    league: "PLL",
  },
  {
    id: "12",
    homeTeam: { id: "WAT", name: "Waterdogs LC", abbreviation: "WAT", record: "6-6" },
    awayTeam: { id: "PHL", name: "Philadelphia Waterdogs", abbreviation: "PHL", record: "7-4" },
    homeScore: 9,
    awayScore: 14,
    status: "final",
    date: "2026-02-21",
    time: "5:00 PM ET",
    venue: "Subaru Park, Chester PA",
    league: "PLL",
  },
];
